version: 0.0
os: linux

hooks:
  # ApplicationStop:
  #   - location: scripts/application_stop.sh
  #     timeout: 60
  #     runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: root