version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: ec2_deployment/stop_container.sh
      timeout: 80
      runas: root
  AfterInstall:
    - location: ec2_deployment/start_container.sh
      runas: root